Repository MarvinKweyu/ColorDetect, pull requests merged in 2021-02, with the labels that each got.

#29 Documentation update
  CHANGES.rst
  colordetect/color_detect.py
  docs/conf.py
  setup.py
Labels: documentation, enhancement

#28 Feature/colour segmentation
  colordetect/color_detect.py
Labels: enhancement

#32 feature: add color segmentation, masking and monochrome effect
  CHANGES.rst
  colordetect/color_detect.py
  colordetect/video_color_detect.py
  docs/_static/car.jpg
  docs/_static/car_only.png
  docs/_static/monochrome-car.png
  docs/conf.py
  docs/index.rst
  docs/segmentation.rst
  setup.py
  tests/test_unit.py
Labels: documentation, enhancement

#33 docs: fix documentation image render
  CHANGES.rst
  docs/colordetect.rst
  docs/conf.py
  docs/getting_started.rst
  docs/index.rst
  docs/modules.rst
  docs/segmentation.rst
  setup.py
Labels: documentation
